config/routes.rb
Juvius::Application.routes.draw do

  
  
  resources :records

  resources :categories 

  devise_for :users
  
  
  resources :users do
    get 'users', :to => 'user#show', :as => :user_root
  end

  root :to => "welcome#show"

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_one :user
  has_many :records
  
  attr_accessible :user_id, :name
  
  scope :user_categories, lambda { |entity| where("user_id >= ?", entity)}
  
end

app/models/record.rb
class Record < ActiveRecord::Base
  has_one :category
  
  acts_as_taggable_on :tags
  
  attr_accessible :category_id, :record_date, :information,:tag_list
  
  scope :records_from_category, lambda { |entity| where("category_id >= ?", entity)}
  
  def self.search(search)
    if search
        find(:all, :conditions => ['information LIKE ?', "%#{search}%"])
      else
        find(:all)
      end
end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :categories
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email,:username, :password, :password_confirmation, :remember_me, :public_id
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  def after_sign_in_path_for(resource)
    user_path(current_user)
  end
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :authenticate_user!

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    #@records = Record.records_from_category(params[:id])
    #@records = Record.records_from_category(params[:id]).paginate(:per_page => 5, :page => params[:page])
    @search_results = Record.records_from_category(params[:id]).search(params[:search])
    @records = @search_results.paginate(:per_page => 20, :page => params[:page])
    if !params[:search].nil?
        @number_of_search_results = @search_results.count
    end
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(params[:category])
    if @category.save
      redirect_to current_user, :notice => "Successfully created category."
    else
      render :action => 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(params[:category])
      redirect_to @category, :notice  => "Successfully updated category."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to user_path(current_user), :notice => "Successfully destroyed category."
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :there_are_categories
  
  def index
    @records = Record.all
  end

  def show
    @record = Record.find(params[:id])
    @category = Category.find(@record.category_id)
  end

  def new
    @record = Record.new
    @categories = Category.all
  end

  def create
    @record = Record.new(params[:record])

    if @record.save
      redirect_to @record, :notice => "Successfully created record."
    else
      render :action => 'new'
    end
  end

  def edit
    @record = Record.find(params[:id])
    @categories = Category.all
  end

  def update
    @record = Record.find(params[:id])
    if @record.update_attributes(params[:record])
      redirect_to @record, :notice  => "Successfully updated record."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @record = Record.find(params[:id])
    @record.destroy
    redirect_to category_path(@record.category_id), :notice => "Successfully destroyed record."
  end
  
  private
    def there_are_categories
        if Category.all.count == 0 then
            redirect_to user_path(current_user), :notice => "There are no categories. You first need to create categories."
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show

    @user_categories = Category.user_categories(params[:id]).paginate(:per_page => 80, :page => params[:page])
    
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController


  def show
    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/catrgories_helper.rb
module CatrgoriesHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
  <%= f.error_messages %>

  <%= f.hidden_field :user_id, :value => current_user.nil? ? nil : current_user.id%>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/categories/edit.html.erb
<% title "Edit Category"%>
<h2><%= (link_to "Main page", user_path(current_user)) + " -> " + (link_to "Category", category_path(@category)) + " -> " + "Edit Category" %></h2>
<br/>

<%= render 'form' %>

<p>
  <%= link_to "Show", @category %>
</p>

app/views/categories/new.html.erb
<% title "New Category" %>
<h2><%= (link_to "Main page", user_path(current_user)) + " -> " + "New Category" %></h2>
<br/>

<%= render 'form' %>

<p><%= link_to "Back", user_path(current_user) %></p>

app/views/categories/show.html.erb
<%title "Category" %>
<h2><%=  (link_to "Main page", user_path(current_user)) + " -> " + (link_to "Category", category_path(@category)) %></h2>
<br/>

<p>
  <strong>Category:</strong>
  <%= link_to @category.name, category_path(@category) %> ( <%= link_to "Edit", edit_category_path(@category) %> |  <%= link_to "Destroy", @category, :confirm => 'Are you sure?', :method => :delete %> )
</p>

<p>
  <strong>Records:</strong>
  
  <%= form_tag category_path(params[:id]), :method => 'get', :id => "records_search" do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

<% if !params[:search].nil? then%>
    Search Results. <%= @number_of_search_results %> records found.
<% end %>

<br/>
<br/>
<table >
  <tr>
    <th width=18%>Record date</th>
    <th width=62%>Information</th>
    <th width=20%>Options</th>
  </tr>
  <% for record in @records %>
    <tr>
      <td style="color:#111111"><%=h record.record_date.to_s(:long) %></td>
      <td style="padding-left:10px;padding-right:10px; color:#111111"><%= record.information %></td>
      <td><%= link_to "Edit", edit_record_path(record) %> <%= link_to "Destroy", record, :confirm => 'Are you sure?', :method => :delete %> <%= link_to "Show", record_path(record) %></td>
    </tr>
    </tr>
  <% end %>
</table>
<br/>
<%= will_paginate @records %>


<p>
  
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Activity tracking" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :defaults %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    
    <div style="width:900px; margin:auto; padding: 10px; border: solid 1px #1D9BD1; text-align:center;color: #333333;">
        <h3><strong>Activity Tracking Module</strong></h1>
    </div>
    
    <div id="container">
    <div id="user_nav">
    <% if user_signed_in? %>
        Hello, <%= current_user.username %>
       <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
       <%= link_to "Main page", user_path(current_user) %>
    <% else %>
        <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
    <% end %>
    </div>
    <br>

       
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      

    
      <div style="width:900px; margin:0px auto;padding: 10px 10px 100px 10px;">
        <%= yield %>
     </div>
    </div>
  </body>
</html>

app/views/records/_form.html.erb
<%= form_for @record do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :category %><br />
    <%= f.select :category_id, @categories.collect {|c| [ c.name, c.id ] }, :selected => @record.nil? ? '' : @record.category_id %>
  </p>
  <p>
    <%= f.label :record_date %><br />
    <%= f.date_select :record_date %>
  </p>
  <p>
    <%= f.label :information %><br />
    <%= f.text_area :information %>
  </p>
  <p>
    <%= f.label :tag_list %><br />
    <%= f.text_field :tag_list %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/records/edit.html.erb
<%title "Edit Record"%>
<h2><%= (link_to "Main page", user_path(current_user)) + " -> " + (link_to "Record", record_path(@record)) + " -> " + "Edit Record" %></h2>
<br/>

<%= render 'form' %>

<p>
  <%= link_to "Show", @record %> | <%= link_to "Back to category", category_path(@record.category_id) %>
</p>

app/views/records/new.html.erb
<% title "New Record" %>

<%= render 'form' %>

<p><%= link_to "Back to Main Page", user_path(current_user) %></p>

app/views/records/show.html.erb
<%title "Record"%>
<h2><%= (link_to "Main page", user_path(current_user)) + " -> " + (link_to "Record", record_path(@record)) %></h2>
<br/>

<p>
  <strong>Category:</strong>
  <%= @category.name %>
</p>
<p>
  <strong>Record Date:</strong>
  <%= @record.record_date %>
</p>
<p>
  <strong>Information:</strong>
  <%=h simple_format(@record.information) %>
</p>

<p>
  <strong>Tags:</strong>

  <% for tag in @record.tags%>
      <%= tag %>
  <% end %>
</p>

<p>
  <%= link_to "Edit", edit_record_path(@record) %> |
  <%= link_to "Destroy", @record, :confirm => 'Are you sure?', :method => :delete %>
  <br/>
  <br/>
  <%= link_to "Back to category", category_path(@record.category_id) %>
</p>

app/views/users/show.html.erb
<%title "Main Page"%>
<h2><%= (link_to "Main page", user_path(current_user)) %></h2>
<br/>
<p>
   <%= link_to "New Category", new_category_path %> | <%= link_to "New Record", new_record_path %>
</p>

<br/>
<% @user_categories.each_with_index do |category,index| %>
    <%= link_to category.name, category_path(category) %>
    
    <% if index%10 == 0 and index!=0 then %>
        <br/>
    <%end%>
<% end %>

<%= will_paginate @user_categories %>

app/views/welcome/show.html.erb
<div style="text-align:center">
<p>
   Wellcome to Activity Tracking Module.
</p>
<p>
  <% if current_user.nil? %>
    <%= link_to "Sign in" , new_user_session_path %>    or     <%= link_to "Register" , new_user_registration_path %>
  <%else%>
    
  <%end%>
  
</p>
</div>

</p>